//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kargo_Takip_Projesi.Models.Veri_Tabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gönderici_Bilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gönderici_Bilgileri()
        {
            this.Kargo_Durum = new HashSet<Kargo_Durum>();
        }
    
        public int Gonderici_Id { get; set; }
        public string Gonderici_Ad { get; set; }
        public string Gonderici_Soyad { get; set; }
        public string Gonderici_Adres { get; set; }
        public string Gonderici_Ilce { get; set; }
        public string Gonderici_Il { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kargo_Durum> Kargo_Durum { get; set; }
    }
}
