//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kargo_Takip_Projesi.Models.Veri_Tabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kargo_Durum
    {
        public int Kargo_Id { get; set; }
        public int Kargo_Gonderici_Kisi { get; set; }
        public int Kargo_Alici_Kisi { get; set; }
        public int Kargo_Urun { get; set; }
        public string Kargo_Islem_Tarihi { get; set; }
        public string Kargo_Durumu { get; set; }
    
        public virtual Alici_Bilgileri Alici_Bilgileri { get; set; }
        public virtual Gönderici_Bilgileri Gönderici_Bilgileri { get; set; }
        public virtual Urun_Bilgileri Urun_Bilgileri { get; set; }
    }
}
