//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kargo_Takip_Projesi.Models.Veri_Tabani
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Kargo_TakipEntities : DbContext
    {
        public Kargo_TakipEntities()
            : base("name=Kargo_TakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alici_Bilgileri> Alici_Bilgileri { get; set; }
        public virtual DbSet<Gönderici_Bilgileri> Gönderici_Bilgileri { get; set; }
        public virtual DbSet<Kargo_Durum> Kargo_Durum { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Urun_Bilgileri> Urun_Bilgileri { get; set; }
        public virtual DbSet<Yonetici_Kayit> Yonetici_Kayit { get; set; }
    }
}
