//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kargo_Takip_Projesi.Models.Veri_Tabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun_Bilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun_Bilgileri()
        {
            this.Kargo_Durum = new HashSet<Kargo_Durum>();
        }
    
        public int Urun_Barkod_Numarasi { get; set; }
        public string Urun_Adi { get; set; }
        public string Urun_Aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kargo_Durum> Kargo_Durum { get; set; }
    }
}
