//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kargo_Takip_Projesi.Models.Veri_Tabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yonetici_Kayit
    {
        public int Yonetici_Id { get; set; }
        public string Yonetici_Kullanici_Adi { get; set; }
        public string Yonetici_Sifre { get; set; }
        public string Yonetici_Email { get; set; }
    }
}
